### ISSUE TITLE
Display diff and prompt confirmation before promoting

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/heroku-pipeline#7]
```
heroku pipeline:promote
Comparing deep-thought-1234-staging to deep-thought-1234...done, deep-thought-1234-staging ahead by 1 commit:
  73ab415  2012-01-01  A super important fix  (Joe Developer)

Are you sure you would like to promote these changes? Type target app name to continue:
deep-thought-1234
Promoting deep-thought-1234-staging to deep-thought-1234...done, v2
```

Also allow optional override with `--confirm` flag.

**Comment by markpundsack** [comment]
We don't prompt for confirmation on `git push`, why would we on promotion? Showing the diff information is a nice touch, and I guess the point is you're giving them an opportunity to read the diff and change their minds, but it seems overall unnecessary to add the hurdle. Alternatively, add something like a `-i` flag to go "interactive" or otherwise show the diff and prompt.

**Comment by ryanbrainard** [comment]
I see your point, but promotion moves the code to a more important environment, so prompting feels warranted. `git push` could also do that, but not in all cases. I don't feel strongly either way on this and trust your judgement.
